version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/services/location-service/src/main/scripts/postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
